using System;


namespace PillarPencil.Test
{
    public class LorumIpsum
    {
        public static string Text = 
@"Lorem ipsum dolor sit amet consectetur adipiscing elit Proin sed massa nec leo finibus accumsan Suspendisse iaculis consequat ipsum sit amet maximus Orci varius natoque penatibus et magnis dis parturient montes nascetur ridiculus mus Phasellus justo nulla vulputate quis enim ac congue interdum orci Curabitur at sodales nibh quis interdum erat Praesent a fermentum leo eget sagittis est Vestibulum scelerisque quam nec luctus porttitor ipsum dolor vehicula ligula eget iaculis quam tellus facilisis dolor Donec sit amet porta nisl Vestibulum ac tortor nisl Nam sit amet laoreet est Aenean tincidunt mauris id est volutpat auctor Donec vehicula felis nibh suscipit accumsan libero molestie vitae
Nam aliquam feugiat iaculis Sed efficitur ipsum et risus tempus viverra Integer nunc purus placerat elementum massa blandit dapibus fermentum leo Fusce auctor sapien turpis Pellentesque nec scelerisque augue eget interdum sapien Maecenas molestie lacus magna id rutrum nunc ultrices non Curabitur vel purus vel augue facilisis pretium Sed pretium diam at iaculis sagittis enim mauris volutpat nulla id gravida purus nibh sit amet ipsum Aenean cursus suscipit urna eget tristique Curabitur facilisis lorem quis suscipit egestas
Pellentesque fringilla hendrerit tempus Nunc nisi nisl luctus vel felis eu egestas rhoncus nulla Mauris mollis maximus metus sit amet facilisis quam sagittis nec In sit amet turpis non sem suscipit ultrices In ac leo condimentum dignissim nisl vitae faucibus nunc Sed lacinia accumsan luctus Sed cursus metus sed congue porttitor eros lacus aliquam enim eu aliquet mauris orci vitae risus Phasellus imperdiet id ex non aliquam Maecenas sed rutrum urna vel dignissim erat Donec ac imperdiet elit Curabitur accumsan mi orci Sed sem turpis imperdiet a luctus et placerat vel elit Suspendisse aliquam velit ut ex interdum commodo
Quisque et purus nisl Vivamus sagittis nisi nec velit efficitur suscipit Vestibulum lacus purus volutpat vitae sagittis vel pretium luctus velit Nam eleifend sagittis tellus In rutrum felis vel tempor lacinia Duis feugiat imperdiet sapien et interdum dolor pulvinar a Phasellus scelerisque consectetur sapien nec dapibus Phasellus id erat velit
Nunc molestie dui elit vitae pellentesque arcu porta a Aenean ultrices dictum magna vitae pulvinar Aliquam dui leo viverra ut lorem non tincidunt tincidunt massa Etiam et nisi lorem Aliquam et sem eu massa ultrices condimentum id vel mauris Ut posuere justo sed mattis interdum Mauris a venenatis ante eu tristique risus Sed non volutpat dui Proin in massa vehicula aliquet orci nec elementum purus
Fusce vitae eros sed augue gravida dapibus Fusce eleifend dignissim elit quis viverra Nullam pulvinar lectus vel tellus lobortis sollicitudin Vivamus aliquet ornare lorem Fusce egestas ante non dictum consequat felis risus ultrices metus id fermentum nulla dui a nisi Sed tempus lacus est Nullam ac aliquet libero Vestibulum lobortis massa at faucibus accumsan Curabitur luctus eros in laoreet iaculis Proin vel elit lacus Fusce faucibus ornare risus ac dapibus nisl pellentesque eget Aliquam nec neque in odio pulvinar accumsan id eget ante Nulla augue velit pellentesque ac augue et vulputate rutrum odio Nunc felis nunc sodales vitae mi vitae pellentesque pharetra eros
Orci varius natoque penatibus et magnis dis parturient montes nascetur ridiculus mus Aliquam at bibendum enim rutrum tincidunt libero Nam et aliquet est id pulvinar sapien Aliquam sit amet ligula eget elit interdum facilisis Aliquam accumsan ligula a nisi eleifend ut posuere metus porta Aenean posuere et purus ac congue Quisque sit amet lectus non justo vulputate aliquet Nullam iaculis dui ultricies quam scelerisque tempor Integer porta est vel velit euismod aliquet Sed aliquam metus sed consectetur suscipit elit nisl imperdiet est nec porta tellus ex et ex Maecenas ut efficitur massa
Aliquam porttitor euismod mi id faucibus mauris feugiat vitae Duis sodales erat quis maximus vulputate Duis malesuada augue vitae rhoncus vulputate Morbi dignissim diam non laoreet ultricies dui velit consectetur magna quis pharetra eros justo quis turpis Nam mattis leo ut tincidunt auctor Nullam ac sagittis erat Aenean est ex commodo at suscipit ut imperdiet quis nisi Cras ac nisi elit Sed eget ligula purus
In hac habitasse platea dictumst Pellentesque euismod urna at eros suscipit rhoncus Ut nec cursus purus Aliquam rutrum et libero quis maximus Morbi et auctor massa Aliquam sed ex id felis aliquet vehicula Integer ac leo vel ipsum ultrices lobortis accumsan et erat Cras nisi massa euismod et vehicula a elementum quis lacus Donec hendrerit tincidunt blandit Cras egestas egestas nisi quis pellentesque lacus iaculis nec Nullam a nunc imperdiet dui ultrices fermentum sed in nunc Sed non gravida ipsum
Proin ac orci eros Maecenas ullamcorper semper nulla non placerat purus cursus aliquam Donec at rutrum lectus Pellentesque convallis lacus ac quam ultricies in porta dolor faucibus Curabitur tristique purus id porttitor varius eros ligula semper ipsum id faucibus dui ex non orci Nam tincidunt lectus interdum feugiat semper Morbi in orci eu mi convallis suscipit
Duis sit amet ligula non lacus vulputate scelerisque eget vitae lectus Nullam neque felis rutrum eget dapibus iaculis tristique ut ex Sed faucibus dapibus mauris non ultricies diam pharetra interdum Proin in laoreet ante Pellentesque dictum fermentum eros quis malesuada mauris volutpat vel Suspendisse vestibulum pretium elit Nam massa elit elementum vitae nisi id sagittis efficitur metus Etiam eget dui volutpat vehicula ipsum quis venenatis libero
Curabitur porttitor nibh rhoncus ipsum porttitor fringilla Morbi porttitor quis neque posuere maximus Proin neque velit tincidunt eget nisl id molestie auctor tellus Duis vestibulum et orci eu fermentum Ut eleifend eleifend fermentum Integer diam dolor vehicula eget justo vitae dictum blandit ipsum Aliquam erat volutpat In sodales enim a hendrerit bibendum Donec finibus dignissim nulla ut vestibulum dolor pretium ac Donec magna tellus euismod ac urna a fringilla cursus mi Sed dapibus nunc ut rhoncus elementum Praesent nec tempor sem Nulla facilisi
Vivamus iaculis purus nibh at iaculis lectus gravida vitae Praesent et arcu at ante auctor sodales Morbi mattis nisl a auctor aliquam dolor purus congue velit sed feugiat tellus tellus vel augue Proin suscipit consectetur semper Etiam vel est vestibulum arcu luctus congue quis non ipsum Sed convallis sapien elementum fermentum libero in luctus ipsum Aenean eget est volutpat congue ex ac maximus est Praesent semper tempus ipsum in lobortis neque faucibus suscipit
Proin vitae mollis sem Mauris suscipit nibh ipsum egestas molestie turpis elementum sit amet Duis accumsan ipsum sed consectetur gravida Donec eget purus ac tellus elementum facilisis Morbi id purus at odio dignissim molestie nec ac quam Integer semper rutrum nisl ac rutrum Integer eu odio elementum odio dignissim tristique eu a lorem Pellentesque id posuere tellus Quisque porttitor fermentum vestibulum Duis a velit laoreet faucibus lectus at vehicula ligula Nulla varius hendrerit euismod Etiam et sapien eu libero tempor suscipit Nunc tincidunt ut tortor sed ultrices Quisque finibus ut tortor ac fermentum Morbi et lacus justo Etiam rutrum felis eu ultrices aliquet purus ligula lobortis eros eget sollicitudin diam nisi in purus
Sed quam nulla accumsan in nunc at congue facilisis sapien In imperdiet orci ut pellentesque consectetur enim metus lobortis lectus et varius nulla nulla eget lorem Praesent cursus orci sapien id pharetra purus auctor ac Fusce a convallis dui sit amet faucibus mi Morbi massa augue euismod sed felis id pretium ultrices mi Nam suscipit pulvinar dictum Integer tristique hendrerit nibh id tempor
Etiam lobortis consectetur massa in rutrum risus sollicitudin vitae Aliquam et metus in dui vestibulum pellentesque Donec ultrices feugiat erat id congue Maecenas aliquet tortor eu velit semper consequat Sed et vehicula tortor Nulla consequat diam eleifend ornare turpis et gravida tellus Cras quis mollis nulla sit amet viverra risus Mauris egestas fermentum nulla non semper Nunc sit amet fringilla nunc
Donec ut eros vitae erat hendrerit efficitur id id enim Suspendisse sodales nec dui ultrices ultrices Sed pharetra eros at neque fringilla sit amet vehicula sem dignissim In hac habitasse platea dictumst Curabitur nec tellus non lectus ultrices egestas accumsan in ipsum Sed in finibus sem Aenean tellus nisl ornare at justo ac congue vestibulum nisl Donec sit amet augue rutrum laoreet sem in consectetur nisl Aenean justo ligula suscipit at mi nec viverra accumsan quam Aenean tempus magna id vestibulum elementum libero purus porttitor nisl ut egestas diam enim in lacus
Nam volutpat faucibus mi vitae condimentum Pellentesque auctor nulla lorem In eleifend commodo purus vel consectetur enim ultricies eu Nullam ipsum diam vehicula ac tempor eu congue maximus risus Vestibulum in semper ligula Nulla aliquam elit in molestie efficitur Donec mollis sapien in enim ultricies sit amet faucibus lorem ullamcorper Nam elit ipsum ullamcorper eu mi eget blandit dignissim eros Phasellus blandit lorem vitae dignissim volutpat
Nullam pretium leo sed consectetur elementum Mauris ac gravida quam et fermentum dolor Quisque suscipit blandit risus non finibus ligula pellentesque non In et ante cursus lacinia nunc at pharetra urna Aenean non varius sapien In elit urna mollis at justo eu condimentum porttitor purus Quisque id ligula dolor Aliquam a condimentum felis id facilisis lectus Quisque iaculis lorem arcu eu ultrices dolor tristique nec Fusce sed interdum augue";
    }
}
